# Generated by Django 4.2.26 on 2026-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('excited', 'Excited'), ('frustrated', 'Frustrated'), ('calm', 'Calm'), ('stressed', 'Stressed')], max_length=50),
        ),
    ]
