# Generated by Django 4.2.26 on 2026-02-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_load_quotes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(check=models.Q(('mood_rating__gte', 1), ('mood_rating__lte', 5)), name='entry_mood_rating_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(check=models.Q(('mood__in', ['happy', 'anxious', 'sad', 'neutral', 'excited', 'frustrated', 'calm', 'stressed'])), name='entry_mood_valid_choice'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(check=models.Q(('title', ''), _negated=True), name='entry_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(check=models.Q(('content', ''), _negated=True), name='entry_content_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='gratitudeitem',
            constraint=models.CheckConstraint(check=models.Q(('item_text', ''), _negated=True), name='gratitudeitem_text_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('text', ''), _negated=True), name='quote_text_not_empty'),
        ),
    ]
